const facultyData = [
  {
    area: "Physics - Thin films",
    id: "08TSHP04",
    file: "/media/shanthi.pdf",
    name: "Ms.K.SHANTHI",
    pos: "Assistant Professor",
    image: "/media/image/Ms._K.Shanthi.jpg",
    order: "22",
    email: "k.shanthi@skct.edu.in",
  },
  {
    area: "Coordination Chemistry",
    id: "08TSHC03",
    file: "/media/santhosh_Website_format_profile.pdf",
    name: "Dr D. SANTHOSH SHANTHAKUMAR",
    pos: "Associate Professor",
    image: "/media/image/Mr.D.Santhosh_Shanthakumar.jpg",
    order: "16",
    email: "d.santhoshshanthakumar@skct.edu.in",
  },
  {
    area: "Coordination  Chemistry",
    id: "14TSHC01",
    file: "/media/NALINI_Profile.pdf",
    name: "Dr N. NALINI",
    pos: "Associate Professor",
    image: "/media/image/Ms.N.Nalini.jpg",
    order: "17",
    email: "n.nalini@skct.edu.in",
  },
  {
    area: "Mathematics- Symmetric Fuzzy Matrix",
    id: "08TSHM02",
    file: "/media/T.Bhavani.pdf",
    name: "Ms. T.BHAVANI",
    pos: "Assistant Professor",
    image: "/media/image/Ms._T.Bhavani.jpg",
    order: "4",
    email: "t.bhavani@skct.edu.in",
  },
  {
    area: "Thin Flims, Nano Materials, Photovoltaic cell, Solar Water Distillation, etc",
    id: "18TSHP01",
    file: "/media/Website_format_profile_R._Ganesh.pdf",
    name: "Dr.R.GANESH",
    pos: "Associate Professor",
    image: "/media/image/Ganesh_R_Phy.jpg",
    order: "20",
    email: "ganesh.r@skct.edu.in",
  },
  {
    area: "Fuzzy Sets",
    id: "11TSHM04",
    file: "/media/leelavathi.pdf",
    name: "Ms. N. LEELAVATHI",
    pos: "Assistant Professor",
    image: "/media/image/Ms._N._Leelavathi_.jpg",
    order: "7",
    email: "n.leelavathi@skct.edu.in",
  },
  {
    area: "Corrosion Science",
    id: "08TSHC06",
    file: "/media/SSS.pdf",
    name: "Ms.S.S.SABITHAMALA",
    pos: "Assistant Professor",
    image: "/media/image/Ms._S.S.Sabithamala.jpg",
    order: "19",
    email: "s.s.sabithamala@skct.edu.in",
  },
  {
    area: "Queueing Theory",
    id: "07TSHM01",
    file: "/media/Website__profile-SHEEBA.pdf",
    name: "Ms. P. SHEEBA RANJINI",
    pos: "Associate professor",
    image: "/media/image/7622_A.jpg",
    order: "3",
    email: "sheebaranjini.p@skct.edu.in",
  },
  {
    area: "Cristal Growth",
    id: "12TSHP02",
    file: "/media/V.Marianandhakumar.pdf",
    name: "Mr. V. MARI ANANDHAKUMAR",
    pos: "Assistant Professor",
    image: "/media/image/Mr._V._Mari_Anandhakumar.jpg",
    order: "23",
    email: "v.marianandhakumar@skct.edu.in",
  },
  {
    area: "Mathematics Statistics",
    id: "08TSHM08",
    file: "/media/H.Shubhajyothi.pdf",
    name: "Ms. H.SHUBHAJYOTHI",
    pos: "Assistant Professor",
    image: "/media/image/Ms._H.Shubhajyothi.jpg",
    order: "5",
    email: "h.shubajyothi@skct.edu.in",
  },
  {
    area: "Solar Water Distillation",
    id: "18TSHP02",
    file: "/media/Website_format_profile_-_Dr._V.Mani-converted.pdf",
    name: "Dr.V.MANIKANDAN",
    pos: "Assistant Professor",
    image: "/media/image/mani.jpg",
    order: "21",
    email: "manikandan.v@skct.edu.in",
  },
  {
    area: "Polymer Chemistry",
    id: "12TSHC01",
    file: "/media/Website_format_profile-_Dr._S._Prabu_s8LkpxX.pdf",
    name: "Dr S. PRABU",
    pos: "Associate Professor",
    image: "/media/image/Mr.S.Prabu.jpg",
    order: "18",
    email: "s.prabu@skct.edu.in",
  },
  {
    area: "Corrosion Science",
    id: "05TSHC01",
    file: "/media/Kanimozhi___Faculty_Profile_-Website_-_PDF_5Tt21gM.pdf",
    name: "Dr K.R.KANIMOZHI",
    pos: "Professor",
    image: "/media/image/Dr._K.R._Kanimozhi.jpg",
    order: "15",
    email: "k.r.kanimozhi@skct.edu.in",
  },
  {
    area: "Topology",
    id: "13TSHM04",
    file: "/media/VakithaBegam.pdf",
    name: "Ms.R.VAKITHABEGAM",
    pos: "Assistant Professor",
    image: "/media/image/Ms.R.VakithaBegam.jpg",
    order: "10",
    email: "r.vakithabegam@skct.edu.in",
  },
  {
    area: "Differential Equations",
    id: "15TSHM06",
    file: "/media/Maheskumar_D.pdf",
    name: "Mr. D. MAHESKUMAR",
    pos: "Assistant Professor",
    image: "/media/image/Mr.Maheskumar.D.jpg",
    order: "13",
    email: "maheskumar.d@skct.edu.in",
  },
  {
    area: "Queueing Theory",
    id: "11TSHM02",
    file: "/media/lg.pdf",
    name: "Ms. L.GOMATHY",
    pos: "Assistant Professor",
    image: "/media/image/Ms__L_Gomathy.jpg",
    order: "6",
    email: "l.gomathy@skct.edu.in",
  },
  {
    area: "Fluid Dynamics, Differential Equation",
    id: "13TSHM01",
    file: "/media/karthi.pdf",
    name: "Mr. S. KARTHIK",
    pos: "Assistant Professor",
    image: "/media/image/Mr.Karthik.S.jpg",
    order: "8",
    email: "karthik.s@skct.edu.in",
  },
  {
    area: "Mathematics",
    id: "14TSHM01",
    file: "/media/Website_format_profile-vp_2OsxGqK.pdf",
    name: "Dr.V.PARIMALA",
    pos: "Associate Professor",
    image: "/media/image/Ms.V.Parimala.jpg",
    order: "2",
    email: "v.parimala@skct.edu.in",
  },
  {
    area: "Queueing Theory",
    id: "15TSHM02",
    file: "/media/B.Lavanya.pdf",
    name: "Ms.B.LAVANYA",
    pos: "Assistant Professor",
    image: "/media/image/Ms.B.Lavanya.jpg",
    order: "11",
    email: "b.lavanya@skct.edu.in",
  },
  {
    area: "Fluid Dynamics",
    id: "14TSHM03",
    file: "/media/D._Vasantha_kumari_-_Website_format_profile.pdf",
    name: "Dr D. VASANTHAKUMARI",
    pos: "Assistant Professor",
    image: "/media/image/Ms.D.Vasanthakumari.jpg",
    order: "1",
    email: "d.vasanthakumari@skct.edu.in",
  },
  {
    area: "Statistical Quality Control- Acceptance Sampling",
    id: "13TSHM03",
    file: "/media/Website_format_profile_Haripriya.pdf",
    name: "Ms.B.HARIPRIYA",
    pos: "Assistant Professor",
    image: "/media/image/Haripriya_pho_qjsYjA4.png",
    order: "9",
    email: "b.haripriya@skct.edu.in",
  },
  {
    area: "Topology",
    id: "20TSHM01",
    file: "/media/Website_format_profile-Santhiya.pdf",
    name: "Ms. S. SANTHIYA",
    pos: "Assistant Professor",
    image: "/media/image/santhiya_-_photo_page-0001.jpg",
    order: "14",
    email: "santhiya.s@skct.edu.in",
  },
  {
    area: "British Literature, American Literature, Journalism and Mass Communication, English Literature",
    id: "",
    file: "/media/Website_format_profile.pdf",
    name: "Ms. B. PAVITHRA",
    pos: "Assistant Professor",
    image: "/media/image/B612_20210330_122909_152.jpg",
    order: "27",
    email: "pavithra.b@skct.edu.in",
  },
  {
    area: "Indian Writing in English",
    id: "02TSHE01",
    file: "/media/Website_format_profile_shanthamani.pdf",
    name: "Ms.R.SHANTHAMANI",
    pos: "Associate professor",
    image: "/media/image/Ms.R.Shanthamani.jpg",
    order: "24",
    email: "r.shanthamani@skct.edu.in",
  },
  {
    area: "Queueing Theory",
    id: "15TSHM04",
    file: "/media/Website_format_profile1_sujipriya.pdf",
    name: "Ms.A.SUJIPRIYA",
    pos: "Assistant Professor",
    image: "/media/image/Ms.A.Sujipriya.jpg",
    order: "12",
    email: "s.sujipriya@skct.edu.in",
  },
  {
    area: "African-American Literature",
    id: "22TSHE02",
    file: "/media/white_image_dyNGxRU.pdf",
    name: "Dr.B.K0GILAVANI",
    pos: "Assistant Professor",
    image: "/media/image/white_image_gu4CooR.jpg",
    order: "26",
    email: "kogilavani.b@skct.edu.in",
  },
  {
    area: "Indian Writing in English",
    id: "22TSHE01",
    file: "/media/white_image.pdf",
    name: "Dr.N.VENUGOPAL",
    pos: "Associate Professor",
    image: "/media/image/white_image.jpg",
    order: "25",
    email: "venugopal.n@skct.edu.in",
  },
  {
    area: "Indian English Literature, Fiction and Poetry",
    id: "22TSHE01",
    file: "/media/white_image_T2LUhvm.pdf",
    name: "Ms.M.GAYATHRI",
    pos: "Assistant Professor",
    image: "/media/image/white_image_TYZUjkX.jpg",
    order: "28",
    email: "gayathri.m@skct.edu.in",
  },
];

export default facultyData;
