const data = {
  rec: [
    { img: "/media/image/accenture.png" },
    { img: "/media/image/amazon.png" },
    { img: "/media/image/amercian_mega.png" },
    { img: "/media/image/amphisoft.png" },
    { img: "/media/image/astrazenca.png" },
    { img: "/media/image/bosch.png" },
    { img: "/media/image/coznizant.png" },
    { img: "/media/image/directi.png" },
    { img: "/media/image/embed_ur.png" },
    { img: "/media/image/exterro.png" },
    { img: "/media/image/hexaware_tech.png" },
    { img: "/media/image/hp.png" },
    { img: "/media/image/ibm.png" },
    { img: "/media/image/infoview.png" },
    { img: "/media/image/infoys.png" },
    { img: "/media/image/torry_haris.png" },
    { img: "/media/image/nation_star.png" },
    { img: "/media/image/virtusa.png" },
    { img: "/media/image/ndot.png" },
    { img: "/media/image/odessa.png" },
    { img: "/media/image/subex.png" },
    { img: "/media/image/trimble.png" },
    { img: "/media/image/wipro.png" },
    { img: "/media/image/zoho.png" },
    { img: "/media/image/vuram.png" },
    { img: "/media/image/aditya_birla.jpg" },
    { img: "/media/image/axis_bank.jpg" },
    { img: "/media/image/bosch.jpg" },
    { img: "/media/image/byjus.jpg" },
    { img: "/media/image/catholic_syrian_bank.jpg" },
    { img: "/media/image/city_union_bank.jpg" },
    { img: "/media/image/coca_cola.jpg" },
    { img: "/media/image/dmart.jpg" },
    { img: "/media/image/federal_bank.jpg" },
    { img: "/media/image/Grand_thornton.jpg" },
    { img: "/media/image/hdfc.jpg" },
    { img: "/media/image/itc.jpg" },
    { img: "/media/image/johnson.jpg" },
    { img: "/media/image/karvy.jpg" },
    { img: "/media/image/nippon_paint.jpg" },
    { img: "/media/image/Logo_of_Soliton_Technologies.png" },
    { img: "/media/image/infoview_PkLEwHs.png" },
    { img: "/media/image/embed_ur_u7dWXkZ.png" },
    { img: "/media/image/tessolve.png" },
    { img: "/media/image/maxeye.png" },
    { img: "/media/image/qubercomm.png" },
    { img: "/media/image/rfpio.png" },
    { img: "/media/image/1_bN0ptwB.jpg" },
    { img: "/media/image/2.png" },
    { img: "/media/image/3_8UZ4jxk.jpg" },
    { img: "/media/image/4.png" },
    { img: "/media/image/5.png" },
    { img: "/media/image/6.png" },
    { img: "/media/image/7.jpeg" },
    { img: "/media/image/8.png" },
    { img: "/media/image/9.jpeg" },
    { img: "/media/image/10.png" },
    { img: "/media/image/11.jpeg" },
    { img: "/media/image/12_yHpDNCi.png" },
    { img: "/media/image/13.png" },
    { img: "/media/image/14.png" },
    { img: "/media/image/15.png" },
    { img: "/media/image/17.jpeg" },
    { img: "/media/image/18.jpeg" },
    { img: "/media/image/19.jpeg" },
    { img: "/media/image/19_WpDSF1M.jpeg" },
    { img: "/media/image/20.png" },
    { img: "/media/image/21.png" },
    { img: "/media/image/23.png" },
    { img: "/media/image/24.png" },
    { img: "/media/image/25.jpeg" },
    { img: "/media/image/Mech_1.jpg" },
    { img: "/media/image/Mech_2.jpg" },
    { img: "/media/image/Mech_3.jpg" },
    { img: "/media/image/Mech_4.jpg" },
    { img: "/media/image/Mech_5.jpg" },
    { img: "/media/image/Mech_6.jpg" },
    { img: "/media/image/Mech_7.jpg" },
    { img: "/media/image/Mech_8.jpg" },
    { img: "/media/image/Mech_9.jpg" },
    { img: "/media/image/Mech_10.jpg" },
    { img: "/media/image/Mech_11.jpg" },
    { img: "/media/image/Mech_12.jpg" },
    { img: "/media/image/Mech_13.jpg" },
    { img: "/media/image/Mech_14.jpg" },
    { img: "/media/image/Mech_15.jpg" },
    { img: "/media/image/Mech_15_eiRyiJR.jpg" },
    { img: "/media/image/Mech_16.jpg" },
    { img: "/media/image/Mech_17.jpg" },
    { img: "/media/image/Mech_18.jpg" },
    { img: "/media/image/Mech_19.jpg" },
    { img: "/media/image/Mech_20.jpg" },
    { img: "/media/image/Robert_Bosch_Logo.JPG" },
    { img: "/media/image/Siemens_logo.JPG" },
    { img: "/media/image/accenture_logo.JPG" },
    { img: "/media/image/tcs_logo.JPG" },
    { img: "/media/image/CTS_logo.JPG" },
    { img: "/media/image/coding_mart_logo.JPG" },
    { img: "/media/image/zoho_logo.JPG" },
    { img: "/media/image/Odessa_logo.JPG" },
    { img: "/media/image/wipro_logo.JPG" },
    { img: "/media/image/RECRUITERS.JPG" },
    { img: "/media/image/JLL.png" },
    { img: "/media/image/GOOD_EARTH.png" },
    { img: "/media/image/ATKINS.png" },
    { img: "/media/image/JAIN.jpg" },
    { img: "/media/image/SOBHA.png" },
    { img: "/media/image/FEEDBACK.jpg" },
    { img: "/media/image/CADEPLOY.png" },
  ],
  test: [
    {
      text: "“Choosing Sri Krishna College of Technology to pursue B.Tech IT was one of the best decisions in my life. The faculty were master’s of the trade, supportive and friendly, the management was keen in the welfare of students and the placement cell was at the top of their feet to ensure a good career for their students. Thanks to SKCT, after 6 years in the Industry working for companies like DELL EMC, I’m at Trinity College Dublin, Ireland for my Master’s and the basic skill set I acquired from SKCT is helping me even now. I would surely vouch for my Alma Mater!”",
      name: "Arun",
      img: "/media/image/IMG-20191001-WA0009.jpg",
    },
    {
      text: '"I am now an entrepreneur for nearly 5 years successfully running my own company UPDATE STUDIOS. I still remember the first time I won a short film contest in SKCT and that was the starting point of my career. From then on, the responsibilities and opportunities they gave me made me find my inner potential. I am overwhelmed by the recognition I am receiving from SKCT and my teachers till today. According to me, if every college finds the  students\' right field of interest and talent and encourage them to work passionately , then their talent will eventually reach out to the world and they will become a star."',
      name: "A. Shamir Mohammed",
      img: "/media/image/IMG-20191012-WA0005.jpg",
    },
    {
      text: "About 10 years back, when I cleared the quarter finals of an international competition organized by Microsoft, the department and staff rallied behind me - giving me support and access to resources to learn and experiment. I crashed out at the semifinals but that set me on a journey - working on Bharat operating system in CDAC, being a contractor in Google, and currently an Engineering Manager in Akamai which handles about 30% of the global internet traffic. This rather unique path all began in the corridors of SKCT.",
      name: "A.Jesso Clarence",
      img: "/media/image/IMG-20191001-WA0008.jpg",
    },
    {
      text: "I don't want to compare my institution with the world class of the masses, but it certainly is above them all. I am what I am today because of this great institution",
      name: "EINSTEIN AMIRTHARAJ",
      img: "/media/image/1_uIWajAx.jpg",
    },
    {
      text: "SKCT is a place of learning, fun, culture, love, literature and many such life preaching activities. It gave me an opportunity to meet different kind of people and learn a number of things. I have received a great support from faculties . I am thankful to the faculties for providing a platform to enhance my skills and an opportunity to showcase them.",
      name: "SALMAN FARISH",
      img: "/media/image/salman.jpg",
    },
    {
      text: "I loved the freedom that College gave me, which made me more independent. My Civil Department treated me like an adult, that really helped me a lot to successfully cross the transition. And, the Opportunities given with magnitude of resources, honed my skills. I would have to admit that I had good teachers, I am grateful. Thank you SKCT.",
      name: "SADHASIVAM .K.J",
      img: "/media/image/sda.jpg",
    },
    {
      text: "I thank the institute and the faculty for all the efforts put in by them. All my batch mates are doing well in their respective jobs which reflect the quality of the students the institute has produced.",
      name: "Ms.Arthini",
      img: "/media/image/Ms.Arthini.jpg",
    },
    {
      text: "It was a wonderful and grateful experience I got from Sri Krishna College of Technology. I am really thankful to all my faculty there who were with me in every circumstance during my four year program",
      name: "Mr.Dhyanesh",
      img: "/media/image/Mr.Dhyanesh.jpg",
    },
    {
      text: 'It’s always true that, "Where there is will there is a way". I came with my dreams into this institution and I am happy now. I thank all the faculty members who always motivated and helped me to overcome my weakness. I am happy with my job.',
      name: "Ms.Shakthi Suganya",
      img: "/media/image/Ms.Shakthi_Suganya.jpg",
    },
    {
      text: 'It is always good to come back to an institute like Sri Krishna college of Technology formerly known as "VLBJCET" where skills have been nurtured and enhanced. This college gave a platform to express ourselves to industry and learn the industry scenario.',
      name: "Ms.Jayashree",
      img: "/media/image/Ms.Jayashree.jpg",
    },
    {
      text: "Many companies came to our college. We had many cultural events in our college also we participated in many cultural events and had fun. Fun was never restricted in our college they wanted us to study and we enjoyed too.",
      name: "Mr.Jayakrishnan Seeralan",
      img: "/media/image/Mr.Jayakrishnan_Serelan.JPG",
    },
    {
      text: "It is a real “wow” feeling after seeing the infrastructure and interacting with staffs when I have visited recently the college campus. Krishna college has transformed very well in terms of its achievement , infrastructure, faculties ..etc…and really a benchmarking university in the region. I was personally able to witness the whole infrastructure, facilities, laboratories and test equipment’s…believe me in my say that “ it is the state of the art “ and “ best in class “ . Secondly, I need to admire the excellent staff members of the college who are very competent and are connecting well with the alumni members to ensure the success with the industry connect. Congratulations to  management, staff’s, alumni’s  and students of the university, I wish you all for more and more continuous success in days to come.",
      name: "Mr. Suresh D, \r\nCEO – Spark Minda Technical Center",
      img: "/media/image/suresh.png",
    },
    {
      text: "My four years at SKCT has been excellent memory to cherish for lifetime. The years spent here have been full of learning opportunities that were full of fun and frolic and sometimes with academic grind that one has to go through. The exposure provided makes you a better man to face the challenges of the competetive world",
      name: "SAUMIA ANN SAMUEL",
      img: "/media/image/saumia.jpg",
    },
    {
      text: "I’m a proud alumnus of batch 2003-2007, Civil Engineering Department,  Sri Krishna College of Technology (formerly VLBJCET). The Civil Engineering Department was very much known as one of the strongest facility among the institutions in Coimbatore even before I joined here. It was known and pronounced for the most skilled faculties and sound facilities that the department and institution have established over the long years. I learned all my fundamental Engineering here in a richly cultivated Environment provided by our mentors. There was no name sake teachings here and hence I have not wanted to skip any classes that easily. Once again to mention, the skill sets of our teachers in both content-wise and the teaching methodology-wise had always kept me on full focus into the subjects. The laboratory facilities were always in full potential to support us in practical learning. Finally, what I’m today as a successful Civil Engineer, is all, the credit of our Civil Engineering Department and the Institution.",
      name: "M.M.VENDHAN",
      img: "/media/image/vendhan.jpg",
    },
    {
      text: 'For the current and future students at SKCT, I would like to say this - "SKCT is one of those great institutions where you can follow your passion, shape your career and give wings to it, no matter what field it is in. There is enough support here for you to achieve all your career goals. And finally, when you gather all the knowledge, spread your wings and fly towards success, make it a point to give back a part of that success to the institution which helped you get there. Keep contributing to its success and thereby, the countless number of students who would walk in after you."',
      name: "Shyam Mohan K",
      img: "/media/image/Shyam_Photo.jpg",
    },
    {
      text: "My overall experience in Department of Instrumentation and control engineering is very positive.The department gave me a favorable circumstance to enhance my technical skills, managerial skills and soft skills and supported me in all possible way.They respect ideas and views of each individual.I feel proud to be the product of ICE Department.",
      name: "Mr. Siddharth (2013 - 2017)(Performance Engineer, Accenture)",
      img: "/media/image/siddharth.jpg",
    },
    {
      text: "It is here where I got my time ,space and people what collected myself towards what I wanted to  do in life.  With an engineering spirit one here can steer oneself  to  interesting opportunities especially in the areas of clean sustainable energy and climate solutions.",
      name: "Mr. Aadhith V.Sathvin (2013 - 2017)(Student - Film and Television Institute of India, Pune)",
      img: "/media/image/aadith.jpeg",
    },
    {
      text: "The Department of Instrumentation & Control Engineering provides a vibrant atmosphere for overall personality enhancement. It has been a phenomenal place to study where everyday is an opportunity & learning experience. Graduates take with them experience, expertize, knowledge & insight helping them along the run of life.",
      name: "Mr. Edwin Shaju (2012 - 2016)(Training Service Engineer @ CHEMTROLS)",
      img: "/media/image/Edwin_Shaju.png",
    },
    {
      text: "SKCT and ICE have given me a lot of wonderful memories. It has helped me a lot to reach where i am now. I sincerely feel grateful to the teachers who made me reach this position in my life. I  thank SKCT and ICE department for being instrumental in my career.",
      name: "Ms. Kavitha Raman(2011 - 2015)(Research Engineer (Non Linear Control), The University of Texas, Dallas )",
      img: "/media/image/kavi.jpg",
    },
    {
      text: "Instrumentation and Control Engineering department has got a dynamic atmosphere and energetic people around always. The exceptional programs and teaching methodologies have given me the confidence to pursue my career in a constructive way. I am deeply grateful to all the faculty members and my friends for their constant encouragement and support. I wish each student the best of luck in all their future endeavors.",
      name: "Ms. Vanishree (2013 - 2017)(Programmer Analyst @ CTS)",
      img: "/media/image/vani.jpg",
    },
    {
      text: 'I strongly believe that there are better and rigorous ways of transforming novice students into expert Instrumentation and Control engineers. This department is like a family. Professors are very highly personable and also motivated. I felt like they really cared about me as a person. This department is a great place for people with new ideas who want a supportive environment. Hey Juniors, "Give yourself time to really explore the various opportunities available in this field matching your goals & interests.',
      name: "Mr. Harish Karunanithy (2013 – 2017)(Financial Aid Advisor, AllinAll Ingredients, Ireland)",
      img: "/media/image/harish.jpg",
    },
    {
      text: "I am really blessed to pursue my Bachelor’s in Engineering from SKCT. It was an awesome experience which could be cherished forever. The serene environment surrounding this college gave the right ambience for an effective knowledge transfer. Beyond all what really made our lives was the knowledge which was imparted to us by the faculty. The faculty of Mechanical Department was so patient and supportive in imparting knowledge to the students. The ownership and the challenges which they give to the students make them industry ready. The strong faculty is really an asset to this institution.",
      name: "Charles Sunny",
      img: "/media/image/charles.jpg",
    },
    {
      text: "When I look 20 year back, we spent great time in SKCT. We were blessed with some of very talented and knowledge staff members who thought us all Engineering basics and subjects. The location of the college is like studying in Hill station with good facilities. Recently, I had an opportunity to visit the campus and stunned to witness the recent developments. PENUMBRA Inter-college functions was very different and provided us platform to experiment and grow other extracurricular activities. I learnt how to teach engineering subjects in manner that all the students able to pay attention in the class and applied it in early part of my professional life as a lecturer. Today, I am successful and have spent more than 15 years in the field of core engineering simulation.",
      name: "Dhandapani S, Technical Consultant, TCS, Chennai",
      img: "/media/image/dhandapani.jpg",
    },
    {
      text: "As i was interested in Electrical I joined in this college the course was good but we had a lot of reading to do to get an all pass we had to work very hard and focus more so that we will get a good job apart from the college hours .\r\nI am happy that I got an offer in CTS.",
      name: "Mr. Anand Vijayan",
      img: "/media/image/Mr.Anand_Vijayan.JPG",
    },
    {
      text: "It’s a wonderful experience in the college and it has a very wide knowledge & developing curriculum! College has good industry exposure and placements are really good and there is a very high conversion ratio. Hostel life is equally good and i developed team working quality and had fun with all students! Everyone is equally talented!",
      name: "Mr.Dinesh Natesan",
      img: "/media/image/Mr.Dinesh_Natesan.JPG",
    },
    {
      text: "Four years of college happened to be the most blessed time. Being an Instrumentation engineer now, was possible only by the experience we gained in four years. Teaching, supporting, encouraging was our department’s key roles.\r\nIt took us some time to understand what exactly is I&C, but pretty sooner we realised that I&C was one of the best courses till date and has big impact on the future as well. One interesting fact is that Instrumentation and control is evolving around us every day.\r\nNot just learning, brought us knowledge in our domain, but practically implementations made us stronger as Instrumentation engineers. Innovation in engineering is definitely possible in our I&C domain. \r\nWe had enough time to learn, understand and implement. So, I feel that I&C is unique, very rare but one of the best emerging courses that is selectively started in very few reputed colleges, to lighten up the lucky Instrumentation engineers to be.",
      name: "Ms. Marina Sophia(2014 - 2018)(Instrumentation Design Engineer, Kavin Engineering)",
      img: "/media/image/marina.jpg",
    },
    {
      text: "SKCT has given me an astonishing platform for the overall growth and development. The campus has excellent infrastructure and is very beautiful with perfect blend of nature. Instrumentation & Control Engineering Department is unmatched. The professors are very friendly, professional and inspiring. The faculty members have always revitalized us to learn through exploits which were very helpful for us throughout our studies. Academics are in congruity with the latest industry trends. It's been a privilege to be a part of this esteemed Department.",
      name: "Mr. Ravi Shankar (2012 - 2016)(Programmer Analyst @ CTS )",
      img: "/media/image/ravi.jpg",
    },
    {
      text: "My four years at SKCT in the Dept. Of ICE have been one of the best learning experiences. I have gained a lot of insight into the various nuances of Instrumentation. I would love to thank all the faculty for their guidance and support in all aspects. A special note of gratitude to our HOD for her constant motivation and emphasis on overall development and unparalleled placement efforts. I am indeed proud and grateful to have graduated from such a vibrant and dynamic department.",
      name: "Mr. Niranjan (2014 - 2018)(Artist Manager, Greenroom Talent Network Pvt.Ltd)",
      img: "/media/image/niranjan.jpg",
    },
    {
      text: "The Department of Instrumentation & Control Engineering focuses on making the world look more simpler by the process of automation. My ICE department has been a great launchpad for young aspirants who dream of building up a future where manual efforts could be reduced by the intervention of advanced control systems and technologies. The department exposes the students of ICE to have a vast experience & exposure to the world of automation.",
      name: "Mr. Gowtham Mariappa.R (2012 - 2016)(Program Analyst @ CTS)",
      img: "/media/image/gow.JPG",
    },
    {
      text: "Minimum class strength made students to be well connected with staff members. The department provides enough space for anyone to aspire & learn things beyond the curriculum.",
      name: "Mr. Vijay Anand (2013 - 2017)(Pursuing Master of Design, Specializing in Visual Media @ IIT Kanpur)",
      img: "/media/image/Vijay_Anand.jpg",
    },
    {
      text: "My four years of education & experience in the department of ICE @ SKCT campus is summed up in 3 words : Friendly - Stress Free - & Good Future. I convey my heartly wishes to all my juniors & wish everyone the best for their future.",
      name: "Mr. Gowthaam Nachimuthu (2011 - 2015)(Research Assistant, Germany)",
      img: "/media/image/gowthaam.jpg",
    },
    {
      text: "Sri Krishna College of Technology aka VLB Janakiammal College of Engineering and Technology is one of the prominent and well renown institution in Coimbatore for mechanical engineering in our period (2004) with its infrastructure developments.  There is a saying in tamil “ Its doesn’t depend on where you study but who teaches you matters a lot ” We are one sort of batch who had those kind of staffs who has brought out our hidden talents, who we are? What we are capable of  and what to achieve our aim? after our graduation. Those thoughts have input seed by seed and now you have seen us like a pollen grains burst out into different parts of the world with unique development in the areas of engineering.",
      name: "Adaikala Raja Palaniswamy",
      img: "/media/image/adaikalraj.jpg",
    },
    {
      text: "80% of students were placed in service based and product based companies. The highest salary is around 12 Lacs per annum. Zoho, Amazon, Wipro, Accenture, Infosys, soliton are the major recruiting companies.60% of students got internship. Average salary is about 4-6 Lacs per annum. Well-equipped computers all over the campus. Clean and hygienic food canteen. Fully equipped Wi-Fi campus. Nice climate.",
      name: "Ms. Anya Raman",
      img: "/media/image/Ms.Anya_Raman.JPG",
    },
    {
      text: "An event named Avanta is popular in our college. Nearly 3500 students are studying in our college. The scholarship facilities are also available here. Sports activities are excellent. Well-equipped computers all over the campus. Clean and hygienic food canteen. Fully equipped Wi-Fi campus. Nice climate. The quality of the facilities in your hostel, the quality of food available in the mess and canteen, medical facilities, sport and games are very nice.",
      name: "Mr.Angesh Khanna",
      img: "/media/image/Mr.Angesh_Khanna.JPG",
    },
    {
      text: "The college has excellent infrastructure. The campus is very neat and clean. All the classrooms are equipped with smart boards. Wi-Fi facilities are available throughout the campus. The library is huge, and the college also has all types of books. Labs are maintained properly. All equipment is available in good condition. Hostel rooms are neat and clean.",
      name: "Mr.Praveen Chandrasekaran",
      img: "/media/image/Mr.Praveen_Chandrasekaran_xLap1pT.jpg",
    },
    {
      text: "The college has excellent infrastructure. The campus is very neat and clean. All the classrooms are equipped with smart boards. Wi-Fi facilities are available throughout the campus. The library is huge, and the college also has all types of books. Labs are maintained properly. All equipment is available in good condition. Hostel rooms are neat and clean.",
      name: "Mr.Praveen ChandraSekaran",
      img: "/media/image/Mr.Praveen_Chandrasekaran.jpg",
    },
    {
      text: "The infrastructure is amazing and the ambience is too good. The college faculty provides a good way to improve on the corporate qualities. The IV and tours are so much fun! The hostel is just like feel-at-home! I learnt about life here! The people here are good and broad minded!",
      name: "Mr.V.Praveen Kumar",
      img: "/media/image/Mr.V.Praveen_Kumar.JPG",
    },
    {
      text: "The environment is friendly inside the campus. The principal and faculties are easily approachable at all times. The campus is completely digitized with smart classrooms. Internship and Industry training opportunities are abundant. I chose to join HP and there is plenty of branded companies , both product and service based that visit our campus (Amazon, Zoho, Infy, Wipro, CTS, Accenture etc., to name a few).",
      name: "Mr. Muthu Natesan",
      img: "/media/image/Mr._Muthu_Natesan.JPG",
    },
    {
      text: "The college faculty was good teachers where very friendly and they helped us a lot by not discouraging us they used to encourage us by telling us to study and they used to never compare us using our marks. It is an excellent environment for learning.",
      name: "Mr.G.Krishnaraj",
      img: "/media/image/Mr.Krishnaraj.JPG",
    },
    {
      text: "Sri Krishna College of Technology is one of the best institution in Coimbatore.Its well know for the standard of education that it provides to the student community. The infrastructure and the environment in the campus does not fail to utter wow anyone visiting the campus. The climate is always mild, misty and pleasant.",
      name: "Ms.S.Akilandeswari",
      img: "/media/image/Ms._S.Akilandeswari.JPG",
    },
    {
      text: "A student’s life is a golden life- said Jawaharlal Nehru. I feel this is very apt statement, because I have spent golden years of my student life in SKCT. It was during those days my personality was moulded in the gracious hands of the faculty members. The facilities by the management and the guidance from the faculty had made me to designate this path",
      name: "Mr Sai Surya Kannan, Student, University of Cininnati , USA",
      img: "/media/image/sai.jpg",
    },
    {
      text: "Delivering an 'Alumni Talk' at my Alma Mater, visiting after more than a decade, was indeed a nostalgic and breath-taking experience. The rejuvenated atmosphere, the vastness of the campus and the facilities within, the vibrant student community, the sincere and committed faculty and staff members of the institution made me feel proud of the institution. I would be delighted to contribute to the institution's success story in some way.\"",
      name: "Mr UMASANKAR P, FOUNDER, BRIGHTMINDSATWORK Consulting Private Limited",
      img: "/media/image/uma.jpg",
    },
    {
      text: "",
      name: "Mr.Anfino serfin, RMIT University, Melbourne",
      img: "/media/image/IMG-20200306-WA0004.jpg",
    },
    {
      text: "My parents are my educators. Since I was young, they rooted interest in education on me, a curiosity towards how learning can improve our realities.\r\n\r\nMy years at VLBJCET widened my perspective on how education system throughout the world works and how these system needs leadership qualities to improve opportunities available in the market. My interactions with peers and faculty, both inside and outside the classroom allowed me to get a better understanding about the importance of Man-agement studies to face the challenges and obstacles in society like ours . \r\n\r\nOur college has always encouraged us on giving equal importance to extra curricular ac-tivities and participating in inter- college management events. It was this balance that made me appreciate and nurture my own skills,  while also breaking new grounds and new ideas.\r\n\r\nVLBJCET had always been a hub of learning for it's students",
      name: "Nazia (2008 – 2010 Batch)",
      img: "/media/image/IMG-20200129-WA0002_9r8tsMw.jpg",
    },
    {
      text: "It is my great pleasure to introduce myself as alumni, as an entrepreneur. During my college days my first priority was power sector.  Immediately after college I started up with 5 employees as small scale industry named Hykon, Now after 26 years from 5 employees we are now 400 plus employees. One thing we should understand is that that there is a big opportunity in front of us. This type of opportunity never happens in India for the last 400 years. You are in the right place at right time. That’s INDIA. It is going to be one of the biggest economy in the world in the coming years. So the only thing in that you have to think big. I am very thankful for my teachers , my college for moulding  me as an entrepreneur and I am really happy to see many faculty  still there in our college and still doing a lot of activities for  moulding the students to be professional. I wish each and every one helping me to achieve.",
      name: "Mr. CHRISTO GEORGE, CEO- HYKON INDIA PVT LTD",
      img: "/media/image/cristo.jpg",
    },
    {
      text: "I Feel proud that I was one of the student of SKCT where i have completed my MBA 2018-2020.The department has made me feel special in each and every aspects of two years and also taught me both the professionalism and culture to be followed throughout my life. SKCT filled with blessings of nature which paved me the platform to learn and enhance my skills in the professional life. Throughout my MBA the most respected faculties played a vital role in all my academic participations as well as my extracurricular and my special thanks to all the faculty members as the supporting pillars of each and every academic as well as personal well wishers forever. SKCT simply awesome to spread the positive vibes to find the potential in myself and prove that in all walks of my life.",
      name: "Vidhya Sankari.M, Senior Education Counsellor, Byju’s\r\nMBA (Batch 2018-2020)",
      img: "/media/image/vidhya.jpg",
    },
    {
      text: "I feel very proud to be a part of SKCT SOM family where I completed my MBA during the academic year 2018-2020.Its my pleasure to thank all my beloved professors who had been a great support system for us by molding us with good managerial skills. Apart from academics, various extracurricular activities and events were conducted which helped us to get exposure and enhance our professional skills. SKCT has been blessed with wonderful nature and friendly atmosphere with full of optimistic vibes. Each and every professor is unique and taught us professionalism and corporate culture in every aspect throughout our MBA journey. They equipped us with great managerial skills which helped us during placements. SKCT helped me to find my inner potential and also the right path in which I wanted to be.",
      name: "Dhivya A, \r\nDepartment Manager Trainee, \r\nDMart.\r\nMBA (2018-2020)",
      img: "/media/image/divya.jpg",
    },
    {
      text: "It was my immense luck and fortune to be the part of Sri Krishna college of technology where I can grow. The entire faculty and department leaves no stone unturned to shape one's future. My two years at skct have been a wonderful experience of learning with prolific exposure to outside. Huge respect, love and devotion for entire faculty members and department. It's their efforts that make me to count myself into better professionals.",
      name: "Dinesh S\r\n(2019 – 2021)\r\nBD – Bajaj Finserv Health limited.",
      img: "/media/image/dinesh.jpg",
    },
    {
      text: "My college has paved a way for my interpersonal growth by providing me opportunities when and wherever possible. They have always given me guidance and support, they have encouraged me to participate in various events which helped me in acquiring the skills required for future of being a business person, and I believe they should continue to motivate students that gaining knowledge from outside world is more efficient and helpful.",
      name: "Neelesh C S, (2019-2021), Management intern , Vita Food Ltd.",
      img: "/media/image/neelesh.jpg",
    },
    {
      text: "The MBA course at SKCT is designed and executed in such a manner that it transforms the all-round skills of students. It enriches each student personally and professionally. The institution promotes not just the academics and marks but also the extra-curriculars. The course is not just about the classroom learning. Faculties encourage the students to explore and do not confine them into a restricted boundary. The journey was full of adventure. However, I could sail through because of the supportive peers and faculties.",
      name: "Preetha S, (Batch 2019-21), Talent Acquisition Intern, Kovai.co",
      img: "/media/image/preetha.jpg",
    },
    {
      text: "I am extremely proud and honored that I was one of the students in SKCT, where I have completed my MBA 2018- 2020. College life is meant to bring personality development, intellectual skills, good communication skills and more ethics. The experience was irreplaceable in each and every aspects of two years. SKCT works on development of student personality, my college improve my skills not only by theoretically but also practically. My faculties are played important role in all my academic participations as well as my extracurricular throughout my MBA. Thanks to all the faculty members as the supporting pillars of each and every academic as well as personal well-wishers forever. SKCT simply awesome to spread the positive vibes to find the potential in myself and prove that in all walks of my life.",
      name: "Dhanuskodi.M, (Batch 2018-2020), Relationship Manager, Home First Finance Corporation.",
      img: "/media/image/dhanuskodi.jpg",
    },
    {
      text: "My experience at Sri Krishna College of Technology was tremendous. The curriculum was challenging but rewarding. It provided me the basics as well as practical expertise in vast areas of Electronics and Communication. The professors in the college inspired my best efforts and helped me in areas where I needed guidance and support. Apart from technical skills, the faculty also helped improve my soft skills. The introduction of Snap Talk enhanced my confidence in public speaking.\r\n   \r\nThe knowledge acquired at SKCT has motivated me to pursue my postgraduate studies in Integrated Circuit Design at Technical University of Munich and Nanyang Technological University, (TUM Asia )Singapore.I am proud to be SKCT alumni and I thank my faculties for shaping my career.",
      name: "Ms U Shwetalaxmi",
      img: "/media/image/shwe.jpg",
    },
    {
      text: "I am grateful to the institution and the faculty members for making my journey as a student so memorable. I thank the Institution to gain knowledge and  also provided top-notch facilities for  growth and development as an individual.",
      name: "Mr.G.Hariesh",
      img: "/media/image/Harish_G.jpg",
    },
    {
      text: "Life at SKCT was a very good experience and those days are important and fun chapters of my life book\r\nOur college is having good industry and academic collaboration, which is the reason many companies are interested in visiting SKCT.\r\nI can proudly say SKCT played a major role in what I am now and I am always grateful for that!",
      name: "Mr. Vishalrajan S\r\nSoftware Engineer \r\nFord Motor Company, Ford GTBC , Chennai",
      img: "/media/image/test1.jpeg",
    },
    {
      text: "It’s been 6 years since I passed out from SKCT with campus offer in-hand and currently I am working as a Consultant in KPMG Global Services Private Limited under Tax Technology. SKCT helped me to achieve this position and build my path in this competitive industry. It provides a wide range of placement opportunities and faculties who guide us to develop our knowledge as per industry standards. SKCT also provides multiple platforms to train our soft skills and Technical skills and help us to come up with flying colours.",
      name: "Ms. Komaleshwari  P\r\nConsultant\r\nKPMG Global Services Private Limited under Tax Technology",
      img: "/media/image/test2.jpeg",
    },
    {
      text: 'It is not an exaggeration to highlight My Alma mater SKCT has equipped me with needful knowledge to enter actual life.  Not just Academics, it gave me a delightful experience of 4 years to co-exist with extraordinary people, be it my Teacher or my friends. SKCT honed my technical expertise to be professional. I can still remember how vibrant my department was in providing great opportunities for potpourri of pupils with unique interests. "கேடுஇல் விழுச்செல்வம்" was just poetic metaphor to me, but SKCT made sure it is literal to say Knowledge is an Immortal asset.',
      name: "Mr.  Prashanth Ram M\r\nSDE-T II, Amazon",
      img: "/media/image/test_3.jpeg",
    },
    {
      text: "SKCT is one of the best institutions to pursue your education. ECE department is like a family. Professors are very experienced and friendly. They are always open for support and to clarify doubts. I thank all the staff who supported me to reach this position in my life .The infrastructure and environment are amazing in the campus. Placement training is excellent. It is the training that has made students to work in their dream jobs. They provide equal importance to sports and extra-curricular activities as well. I am proud to be an SKCTian.",
      name: "Pavithra Arumugam \r\nSenior Quality Engineer, LTI Mindtree",
      img: "/media/image/test_4.jpeg",
    },
    {
      text: "SKCT is a place with a blend of lush green campus and a magnificent infrastructure. It provides a platform to students to explore a great opportunity to increase their knowledge and skill-set. It has an exposure to innovative teaching and practical learning which moulds the students in grooming themselves to be a corporate professional. The faculties are very friendly, supportive and inspiring.\r\nThe training and placement department supports in bringing in the reputed companies and helps the students in getting placed. Overall it’s a complete package of learning with fun. I am glad to be a part of SKCT - SOM family.\r\n\r\n-BHAKTHI.H.BHATT",
      name: "",
      img: "/media/image/Bhakthi-Picture_7lzUCQk.png",
    },
    {
      text: "I am writing to express my heartfelt appreciation and gratitude for the exceptional education and experiences I have gained during my time at Sri Krishna College of Technology, specifically in the Department of Mechanical Engineering.\r\nWhen I enrolled at Sri Krishna College of Technology, I had high expectations for my academic journey. However, I am delighted to say that the institution and the department exceeded all my initial aspirations. The dedication and commitment demonstrated by the faculty and staff have played a pivotal role in shaping me into a competent mechanical engineer and preparing me for a successful career.\r\nOne of the remarkable aspects of SKCT is the exceptional faculty within the Department of Mechanical Engineering. Their vast knowledge, industry experience, and passion for teaching have not only made the learning process engaging but have also inspired us to push our limits and think creatively. I am truly grateful for their approachability and willingness to go the extra mile to support and mentor students like me.\r\nThe curriculum offered by the Department of Mechanical Engineering is well-designed and up-to-date, catering to the ever-evolving demands of the industry. The combination of theoretical knowledge and practical applications through hands-on projects, laboratory experiments, and industry collaborations has provided me with a holistic understanding of mechanical engineering principles. I feel confident in my abilities to tackle real-world challenges and contribute meaningfully to the field.\r\nFurthermore, the infrastructure and facilities provided by  SKCT are commendable. The well-equipped laboratories, state-of-the-art workshops, and access to cutting-edge technology have played a pivotal role in enhancing our technical skills. The college library, with its vast collection of books, research papers, and online resources, has been a valuable asset in supporting our academic pursuits.\r\nThe inclusive campus life at  SKCT is also worth mentioning. The extracurricular activities, clubs, and societies have provided ample opportunities for personal growth, leadership development, and the formation of lifelong friendships. Additionally, the career guidance and placement cell have been proactive in organizing industry interactions, internships, and job fairs, ensuring that students are well-prepared for their professional journeys.\r\nI consider myself fortunate to have been a part of Sri Krishna College of Technology and the Department of Mechanical Engineering. The knowledge, skills, and experiences gained during my time here have provided a solid foundation for my future endeavors. I am confident that the education I received will enable me to excel in the field of mechanical engineering and make significant contributions to society.\r\nI would like to take this opportunity to express my deepest gratitude to the entire faculty, staff, and administration of SKCT for their unwavering support and commitment to excellence. I would wholeheartedly recommend Sri Krishna College of Technology and the Department of Mechanical Engineering to any aspiring engineer seeking a comprehensive and enriching educational experience",
      name: "Karuppusamy G,  Senior Executive Industrial Engineer, Whirlpool Corporation",
      img: "/media/image/DSC_2337.JPG",
    },
    {
      text: "The true strength of the B.E program at Sri Krishna College of Technology lies in its multifariously talented professors, its continuous learning support, and its undeniably priceless alumni network. The program is built in such a way that every student curates their learning journey, letting them shape the future as per their aspirations. Located in one of the most aesthetically pleasing parts of Coimbatore, the college emphasizes making education exciting and accessible to all. The unwavering desire to become better is a true testament to what the college stands for. My Bachelors at SKCT has shaped and defined who I am today. It has helped me scale new heights since I always found resources inside the college to accomplish my dreams. I can assure you that every alum feels the same and wears the SKCT tag of honor.",
      name: "Viren J Dave,  MBA student at the University of Alberta, Canada.",
      img: "/media/image/20220813_101323_1.jpg",
    },
    {
      text: "My journey at SKCT was the cornerstone of my success. The solid foundation I built during my bachelor's degree provided me with the essential skills and knowledge to embark on a path of success. It propelled me to pursue a master's degree at Cardiff University (A Russell Group of University) with a scholarship, in the United Kingdom, and I am now a fully-funded doctoral researcher at Loughborough University in the U.K., where I am directing an innovative initiative on \"Renewable Energy from Waste\". I owe a significant part of my success to the exceptional faculty members at SKCT who not only shaped my academic journey during my bachelor's but continue to influence and inspire me in my pursuit of knowledge and innovation. They were my biggest ladder towards achieving my dreams, and I am forever grateful for their guidance and mentorship.",
      name: "K.K.Pranesh,\r\nDoctoral Researcher, \r\nLoughborough University,\r\nEngland, United Kingdom.",
      img: "/media/image/Pranesh.jpeg",
    },
    {
      text: "College memories are something that I’ll cherish throughout my life, because it is a very\r\nvaluable experience in life with tons of nostalgic moments. The most important four years of\r\nmy career started here at SKCT. I can never forget the contribution of the CSE Department,\r\nmy faculty, and Placement cell towards helping me develop those crucial skills which\r\nallowed me to hit the ground running and have success in various roles so far. The faculty\r\nhere are very supportive, providing us freedom to explore and excel in our areas of interest\r\nto bring out the best in us. We were given opportunities to organize several workshops and\r\nparticipate in many programs which I found to be rewarding in every aspect. I feel I use the\r\nknowledge learned from my degree every day in my career. I currently work with ZetaOpt\r\n(LLC) as a Programmer/Infrastructure Consultant. In spite of having a 6-year break, I could\r\nresume my career solely due to these foundations. I’m deeply indebted to SKCT for being a\r\npart of my crucial formative years and nurturing my ambitions and transforming me into a\r\nprofessional. I would attribute the credit for my 1st Rank & GOLD MEDAL in B.E. Computer\r\nScience 2011 from Anna University, Coimbatore, to my alma-mater. I always look forward to\r\nseeing how many lives SKCT has touched, and I can only imagine how many more await.\r\n\r\n\r\nI am NOW, and ALWAYS will be, a PROUD SKCT ALUMNA.",
      name: "Swathi Garimella",
      img: "/media/image/WhatsApp_Image_2023-09-20_at_6.00.10_PM.jpeg",
    },
  ],
};

export default data;
