const facultyData = [
  {
    area: "Machine Learning",
    id: "12TITD01",
    file: "/media/Christy_LBuOnoa.pdf",
    name: "Ms.T.Sangeetha",
    pos: "Assistant Professor",
    image: "/media/image/sangeetha.jpg",
    order: "8",
    email: "t.sangeetha@skct.edu.in",
  },
  {
    area: "Cloud Computing,\r\nWireless Network",
    id: "07TMCA01",
    file: "/media/Dr.A.Christy_Jeba_Malar.pdf",
    name: "Dr.A.Christy Jeba Malar",
    pos: "Associate Professor",
    image: "/media/image/christy.jpg",
    order: "2",
    email: "a.christyjebamalar@skct.edu.in",
  },
  {
    area: "Mobile Adhoc\r\nNetworks, IoT",
    id: "06TITD03",
    file: "/media/R.Suganya.pdf",
    name: "Dr.R.Suganya",
    pos: "Associate Professor",
    image: "/media/image/suganya.jpg",
    order: "3",
    email: "r.suganya@skct.edu.in",
  },
  {
    area: "Internet of Things",
    id: "11TITD04",
    file: "/media/lavanya_zv7L4mf.pdf",
    name: "Dr.G.Lavanya",
    pos: "Associate Professor",
    image: "/media/image/lavanya.jpg",
    order: "5",
    email: "g.lavanya@skct.edu.in",
  },
  {
    area: "Machine Learning , Artificial Intelligence",
    id: "16TITD01",
    file: "/media/Dr.T.Rajesh_Kumar_-_Profile.pdf",
    name: "Dr.T.Rajesh Kumar",
    pos: "Associate Professor",
    image: "/media/image/rajesh.jpg",
    order: "4",
    email: "rajeshkumar.t@skct.edu.in",
  },
  {
    area: "Communication & Networking, IoT, Cognitive Networks",
    id: "09TITD03",
    file: "/media/A.Sureshkumar.pdf",
    name: "Mr.A.Sureshkumar",
    pos: "Assistant Professor",
    image: "/media/image/sureshkumar.jpg",
    order: "7",
    email: "a.sureshkumar@skct.edu.in",
  },
  {
    area: "Blockchain",
    id: "15TITD04",
    file: "/media/M.Malathi.pdf",
    name: "Ms.M.Malathi",
    pos: "Assistant Professor",
    image: "/media/image/Malathi.jpg",
    order: "12",
    email: "m.malathi@skct.edu.in",
  },
  {
    area: "Block Chain",
    id: "17TITD01",
    file: "/media/Madumidha-Faculty_Profile_ZcbMVT2.pdf",
    name: "Ms.S.Madumidha",
    pos: "Assistant Professor",
    image: "/media/image/madhu.jpg",
    order: "14",
    email: "madumidha.s@skct.edu.in",
  },
  {
    area: "Machine Learning",
    id: "14TITD05",
    file: "/media/Faculty_Profile_Mythili.pdf",
    name: "Ms.K.Mythili",
    pos: "Assistant Professor",
    image: "/media/image/mythili.jpg",
    order: "10",
    email: "k.mythili@skct.edu.in",
  },
  {
    area: "Big data, IoT",
    id: "14TITD01",
    file: "/media/Faculty_Profile_muthu.pdf",
    name: "Ms.S.Muthulakshmi",
    pos: "Assistant Professor",
    image: "/media/image/muthu.jpg",
    order: "9",
    email: "s.muthulakshmi@skct.edu.in",
  },
  {
    area: "Data Analytics",
    id: "17TITD04",
    file: "/media/Priyadharshini_Faculty_profile.pdf",
    name: "Ms.S.Priyadharshini",
    pos: "Assistant Professor",
    image: "/media/image/priya_GCDzjvP.jpg",
    order: "16",
    email: "priyadharshini.s@skct.edu.in",
  },
  {
    area: "Data Mining",
    id: "17TITD02",
    file: "/media/Abinaya_-_Name_Faculty_Profile.pdf",
    name: "Ms.K.Abinaya",
    pos: "Assistant Professor",
    image: "/media/image/abinaya.jpg",
    order: "15",
    email: "abinaya.k@skct.edu.in",
  },
  {
    area: "Image Processing",
    id: "15TITD03",
    file: "/media/Faculty_Profile_-Ms_D_Ranjani.pdf",
    name: "Ms.D.Ranjani",
    pos: "Assistant Professor",
    image: "/media/image/ranjani.jpg",
    order: "11",
    email: "d.ranjani@skct.edu.in",
  },
  {
    area: "Networking",
    id: "19TITD02",
    file: "/media/Faculty_Profile_-P.ALAGUVATHANA.pdf",
    name: "Ms.P.Alaguvathana",
    pos: "Assistant Professor",
    image: "/media/image/P.ALAGUVATHANA.jpg",
    order: "18",
    email: "alaguvathana.p@skct.edu.in",
  },
  {
    area: "Data Analytics, \r\nCloud Computing",
    id: "15TITD07",
    file: "/media/Roopa_Faculty_Profile.pdf",
    name: "Ms.V.Roopa",
    pos: "Assistant Professor",
    image: "/media/image/Roopa_Np.JPG",
    order: "13",
    email: "v.roopa@skct.edu.in",
  },
  {
    area: "Software Engineering",
    id: "19TITD03",
    file: "/media/sindhumeena.pdf",
    name: "Ms.K.Sindhu Meena",
    pos: "Assistant Professor",
    image: "/media/image/sindhu.jpg",
    order: "19",
    email: "sindhumeena.k@skct.edu.in",
  },
  {
    area: "Cloud Computing, Big\r\nData",
    id: "18TITD03",
    file: "/media/reshma.pdf",
    name: "Ms. S.Reshma Sultana",
    pos: "Assistant Professor",
    image: "/media/image/reshma.jpg",
    order: "17",
    email: "reshma.s@skct.edu.in",
  },
  {
    area: "Machine Learning",
    id: "20TITD01",
    file: "/media/Admit_Card___NITTT_SvYBnz2.pdf",
    name: "Ms.S.Subhakala",
    pos: "Assistant Professor",
    image: "/media/image/IT_Hod_3TKfjYT.JPG",
    order: "20",
    email: "s.subhakala@skct.edu.in",
  },
  {
    area: "Image processing",
    id: "18TITD01",
    file: "/media/Dr.R.Rameshkumar.pdf",
    name: "Dr.R.Rameshkumar",
    pos: "Professor",
    image: "/media/image/1._Ramesh_1.JPG",
    order: "1",
    email: "rameshkumar.r@skct.edu.in",
  },
  {
    area: "Internet of Things",
    id: "21TITD01",
    file: "/media/Admit_Card___NITTT.pdf",
    name: "Dr.Suma Sira Jacob",
    pos: "Associate Professor",
    image: "/media/image/IT_Hod_LNkR6mW.JPG",
    order: "6",
    email: "sumasirajacob@skct.edu.in",
  },
  {
    area: "Natural Language Processing",
    id: "20TITD02",
    file: "/media/Admit_Card___NITTT_nQYPJs4.pdf",
    name: "Ms.G.Remmiya Devi",
    pos: "Assistant Professor",
    image: "/media/image/IT_Hod_S2p40NS.JPG",
    order: "21",
    email: "remmiyadevi@skct.edu.in",
  },
  {
    area: "Artificial Intelligence",
    id: "20TITD03",
    file: "/media/Admit_Card___NITTT_cYObtmm.pdf",
    name: "Ms.G.V.Aarthi",
    pos: "Assistant Professor",
    image: "/media/image/IT_Hod_GqsAHZe.JPG",
    order: "22",
    email: "aarthi@skct.edu.in",
  },
  {
    area: "Artificial Intelligence",
    id: "20TITD04",
    file: "/media/Admit_Card___NITTT_cCmAi80.pdf",
    name: "Ms.K.Dhanya",
    pos: "Assistant Professor",
    image: "/media/image/IT_Hod_tPyk4PV.JPG",
    order: "23",
    email: "dhanya@skct.edu.in",
  },
  {
    area: "Internet of Things",
    id: "20TITD05",
    file: "/media/Admit_Card___NITTT_rWdvjvg.pdf",
    name: "Ms.P.Poongodi",
    pos: "Assistant Professor",
    image: "/media/image/IT_Hod_7jLmd56.JPG",
    order: "24",
    email: "poongodi@skct.edu.in",
  },
  {
    area: "Machine Learning",
    id: "20TITD04",
    file: "/media/Admit_Card___NITTT_ADtWO7R.pdf",
    name: "Ms.M.Karmukil",
    pos: "Assistant Professor",
    image: "/media/image/IT_Hod_aCXbOcl.JPG",
    order: "25",
    email: "karmukil@skct.edu.in",
  },
  {
    area: "Image processing",
    id: "20TITD04",
    file: "/media/Admit_Card___NITTT_76ufo5Q.pdf",
    name: "Mr.A.Ponravikumar",
    pos: "Assistant Professor",
    image: "/media/image/IT_Hod_h8FVOAs.JPG",
    order: "26",
    email: "ponravikumar@skct.edu.in",
  },
];

export default facultyData;
