const facultyData = [
  {
    area: "Power System Engineering",
    id: "17TEEE14",
    file: "/media/15.Faculty_Profile-Sukanya.G.pdf",
    name: "Ms.G.Sukanya",
    pos: "Assistant Professor",
    image: "/media/image/Ms.G.Sukanya.jpg",
    order: "13",
    email: "g.sukanya@skct.edu.in",
  },
  {
    area: "Power Electronics and Drives",
    id: "17TEEE08",
    file: "/media/8.Faculty_Profile_-_Saravanan.pdf",
    name: "Dr.S.Saravanan",
    pos: "Assistant Professor",
    image: "/media/image/Dr.S.Saravanan.jpg",
    order: "4",
    email: "saravanan.s@skct.edu.in",
  },
  {
    area: "Power Electronics and Drives",
    id: "15TEEE09",
    file: "/media/18.Faculty_Profile_-_Abirami.pdf",
    name: "Ms.S.Abirami",
    pos: "Assistant Professor",
    image: "/media/image/Ms.S.Abirami.jpg",
    order: "14",
    email: "s.abirami@skct.edu.in",
  },
  {
    area: "Power Electronics and Drives",
    id: "17TEEE11",
    file: "/media/28.Faculty_Profile_-Bharani_Prakash.pdf",
    name: "Mr.T.Bharani Prakash",
    pos: "Assistant Professor",
    image: "/media/image/Mr.T.Bharani_Prakash.jpg",
    order: "21",
    email: "bharaniprakash.t@skct.edu.in",
  },
  {
    area: "VLSI Design",
    id: "17TEEE04",
    file: "/media/14.Faculty_Profile-Gayathri_A.pdf",
    name: "Ms.A.Gayathri",
    pos: "Assistant Professor",
    image: "/media/image/Ms.A.Gayathri.jpg",
    order: "19",
    email: "a.gayathri@skct.edu.in",
  },
  {
    area: "Applied Electronics",
    id: "19TEEE04",
    file: "/media/35.Faculty_Profile-Usha_nanthini.pdf",
    name: "Ms.S.Usha Nanthini",
    pos: "Assistant Professor",
    image: "/media/image/Ms.Usha_Nanthini.jpg",
    order: "25",
    email: "ushananthini.s@skct.edu.in",
  },
  {
    area: "Power Electronics and Drives",
    id: "15TEEE08",
    file: "/media/19.Faculty_Profile-_J.Joys_Nancy.pdf",
    name: "Ms.J.Joys Nancy",
    pos: "Assistant Professor",
    image: "/media/image/Ms.J.JoysNancy.jpg",
    order: "15",
    email: "j.joyanancy@skct.edu.in",
  },
  {
    area: "Power Electronics and Drives",
    id: "17TEEE02",
    file: "/media/26.Faculty_Profile_-_lenin.pdf",
    name: "Mr.P.Lenin Pugalhanthi",
    pos: "Assistant Professor",
    image: "/media/image/Mr.Lenin_Pughalenthi.jpg",
    order: "20",
    email: "leninpugal@skct.edu.in",
  },
  {
    area: "Applied Electronics",
    id: "17TEEE03",
    file: "/media/25.Faculty_Profile_-_manimegalai.pdf",
    name: "Ms.V.Manimegalai",
    pos: "Assistant Professor",
    image: "/media/image/Ms.V.Manimegalai.jpg",
    order: "18",
    email: "manimegalai.v@skct.edu.in",
  },
  {
    area: "Embedded Systems",
    id: "",
    file: "/media/29.Faculty_Profile_-poongothai.pdf",
    name: "Ms.T.Poongothai",
    pos: "Assistant Professor",
    image: "/media/image/Ms.T.Pongothai.jpeg",
    order: "22",
    email: "poongothai.t@skct.edu.in",
  },
  {
    area: "Control and Instrumentation",
    id: "19TEEE05",
    file: "/media/38.Faculty_Profile_-_Magdalin_Mary.pdf",
    name: "Ms.D.Magdalin Mary",
    pos: "Assistant Professor",
    image: "/media/image/Ms.Magadlin_mary.jpg",
    order: "27",
    email: "magdalinmary.d@skct.edu.in",
  },
  {
    area: "Control and Instrumentation Engineering",
    id: "18TEEE05",
    file: "/media/21.Faculty_Profile-Swapna.pdf",
    name: "Ms.P.Swapna",
    pos: "Assistant Professor",
    image: "/media/image/Ms.P.Swapna.jpg",
    order: "24",
    email: "p.swapna@skct.edu.in",
  },
  {
    area: "Power Electronics and Drives",
    id: "18TEEE03",
    file: "/media/31.Faculty_Profile-suresh_y438OyR.pdf",
    name: "Dr.K.P.Suresh",
    pos: "Assistant Professor",
    image: "/media/image/Mr.K.P.Suresh.jpg",
    order: "8",
    email: "sureshkp@skct.edu.in",
  },
  {
    area: "Applied Electronics",
    id: "17TEEE06",
    file: "/media/13.Faculty_Profile-Elakya_A.pdf",
    name: "Ms.A.Elakiya",
    pos: "Assistant Professor",
    image: "/media/image/Ms.A.Elakiya.jpg",
    order: "12",
    email: "a.elakkiya@skct.edu.in",
  },
  {
    area: "Power Electronics and Drives",
    id: "18TEEE01",
    file: "/media/30.Faculty_Profile_senthilkumar.pdf",
    name: "Dr.R.Senthil Kumar",
    pos: "Assistant Professor",
    image: "/media/image/Mr.R.senthil_kumar.jpg",
    order: "9",
    email: "senthilkumar.r@skct.edu.in",
  },
  {
    area: "Applied Electronics",
    id: "16TEEE01",
    file: "/media/20.Faculty_Profile-devi.R_pYt3pGC.pdf",
    name: "Dr.R.Devi",
    pos: "Assistant Professor",
    image: "/media/image/Ms.R.Devi.jpg",
    order: "7",
    email: "devi.r@skct.edu.in",
  },
  {
    area: "Power Electronics and Drives",
    id: "19TEEE07",
    file: "/media/39.Faculty_Profile_-_Santhosh_AGBFfa9.pdf",
    name: "Dr.P.Santhosh",
    pos: "Assistant Professor",
    image: "/media/image/Mr.P.Santhosh.jpg",
    order: "5",
    email: "santhosh.p@skct.edu.in",
  },
  {
    area: "Power Electronics & Drives",
    id: "21TEEE01",
    file: "/media/Lijo__SKCT_Faculty_Profile.pdf",
    name: "Dr.Lijo Jacob Varghese",
    pos: "Professor",
    image: "/media/image/Lijo_jacob_Varghese.jpg",
    order: "1",
    email: "lijojacobvarghese@skct.edu.in",
  },
];

export default facultyData;
