import homeCover from './asserts/11.png'

const homeData = {
  dname: "Electronics and Communication Engineering",
  mission:
    "Equipping faculty members with knowledge in cutting-edge technologies through various programs.\r\nImparting quality education to meet the requirements of all stakeholders with the help of well-qualified and experienced faculty resources.\r\nNurturing competent professionals through extra and co-curricular activities.\r\nTo promote research and development activities by setting up new research facilities and industrial interaction.\r\nAccomplishing the technological needs of the society.",
  certificate: "Accredited by NBA under Tier-I Category",
  name: "ECE",
  vision:
    "To produce technical manpower of global standards in Electronics and\r\nCommunication Engineering with capabilities of adapting to new challenges to address the societal needs.",
  image: homeCover,
  about:
    "Started in the year 1985, the Department of ECE has grown higher and is considered as one of the well-equipped departments across the state in terms of infrastructure, Curriculum and Content quality and quality of teaching faculty. While building a solid foundation of the fundamentals, the students are also exposed to emerging trends in the industry and are moulded to be quality professionals of the future. Department of Electronics and Communications Engineering aims at providing T- shaped learning through stream-based electives where students are provided with the choice of getting specialized in any one of the thrust areas like VLSI, Embedded Systems, Communication Engineering, Networks, Image and video processing. The department houses Electronics Sector Skills Council of India sponsored Centre of Excellence in VLSI and Embedded Systems (One of its Kind across Tamilnadu) to develop skilled manpower under the scheme of Skill India and Start-up India to meet the vision of the country, 'Make in India'. Department of Electronics and Communication Engineering has a sanctioned intake of 180 by AICTE and offers UG, PG and PhD Programmes in ECE. Department of ECE is accredited by NBA and permanently affiliated to Anna University, Chennai.",
  academiics: [
    {
      name: "peo",
      details:
        "Graduates will be able to \r\n\r\nPEO1: Apply the broad fundamental concepts of mathematics and science in Electronics and Communication Engineering to be competent enough in their chosen careers.\r\n\r\nPEO2: Innovatively design, simulate, develop, implement and test hardware and software components for offering solution to real life problems and also to demonstrate effective communication skills, the ability to work well either individually or as part of a team.\r\n\r\nPEO3: Become scientists, technocrats and business leaders by utilizing an intellectual environment through Centres of Excellence in research and development oriented emerging technologies and intensive training.\r\n\r\nPEO4: Be a good human being and responsible citizen for the overall welfare of the society.",
    },
    {
      name: "po",
      details:
        "Graduates of Electronics and Communication Engineering program of Sri Krishna College of Technology will have the ability to \r\n\r\nPO1: Engineering knowledge: Apply the knowledge of mathematics, science, engineering fundamentals, and an engineering specialization to the solution of complex engineering problems.\r\n\r\nPO2: Problem analysis:  Identify, formulate, review research literature, and analyze complex engineering problems reaching substantiated conclusions using first principles of mathematics, natural sciences, and engineering sciences.\r\n\r\nPO3: Design/development of solutions: Design solutions for complex engineering problems and design system components or processes that meet the specified needs with appropriate consideration for the public health and safety, and the cultural, societal, and environmental considerations.\r\n\r\nPO4: Conduct investigations of complex problems: Use research-based knowledge and research methods including design of experiments, analysis and interpretation of data, and synthesis of the information to provide valid conclusions.\r\n\r\nPO5: Modern tool usage: Create, select, and apply appropriate techniques, resources, and modern engineering and IT tools including prediction and modelling to complex engineering activities with an understanding of the limitations.\r\n\r\nPO6: The engineer and society: Apply reasoning informed by the contextual knowledge to assess societal, health, safety, legal and cultural issues and the consequent responsibilities relevant to the professional engineering practice.\r\n\r\nPO7: Environment and sustainability: Understand the impact of the professional engineering solutions in societal and environmental contexts, and demonstrate the knowledge of, and need for sustainable development.\r\nPO8: Ethics: Apply ethical principles and commit to professional ethics and responsibilities and norms of the engineering practice.\r\n\r\nPO9: Individual and team work: Function effectively as an individual, and as a member or leader in diverse teams, and in multidisciplinary settings.\r\n\r\nPO10:  Communication: Communicate effectively on complex engineering activities with the engineering community and with society at large, such as, being able to comprehend and write effective reports and design documentation, make effective presentations, and give and receive clear instructions.\r\n\r\nPO11: Project management and finance: Demonstrate knowledge and understanding of the engineering and management principles and apply these to one’s own work, as a member and leader in a team, to manage projects and in multidisciplinary environments.\r\n\r\nPO12: Life-long learning: Recognize the need for, and have the preparation and ability to engage in independent and life-long learning in the broadest context of technological change.",
    },
    {
      name: "pso",
      details:
        "A graduate of the Electronics and Communication Engineering Program of Sri Krishna College of Technology will demonstrate: \r\n\r\nPSO1: Professional Skills: An ability to understand the fundamental concepts in Electronics & Communication Engineering and to apply them to various areas, like Analog & Digital Electronic Systems, Signal & Image Processing, VLSI & Embedded systems, wired & wireless communication networks etc., in the design and implementation of complex systems.\r\n\r\nPSO2: Problem-Solving Skills: An ability to solve complex Electronics and communication Engineering problems in areas, like Analog & Digital Electronic Systems, Signal & Image Processing, VLSI & Embedded systems, wired & wireless communication networks etc., using latest hardware and software tools, along with analytical skills to arrive cost effective and appropriate solutions.",
    },
  ],
};

export default homeData;