const facultyData = [
  {
    area: "Finance & Marketing",
    id: "18TMBA04",
    file: "/media/9._Karthikeyan_N.pdf",
    name: "Mr.N. Karthikeyan",
    pos: "Assistant Professor",
    image: "/media/image/9.Mr.N.karthikeyan.jpg",
    order: "6",
    email: "karthikeyan.n@skct.edu.in",
  },
  {
    area: "Finance & Marketing",
    id: "17TMBA06",
    file: "/media/6.PRASATH_Profile.pdf",
    name: "Mr.R.Saravanan",
    pos: "Assistant Professor",
    image: "/media/image/5.Mr.R.Saravanan.jpg",
    order: "4",
    email: "saravanan.r@skct.edu.in",
  },
  {
    area: "Marketing and Finance",
    id: "21TMBA01",
    file: "/media/P.Thennarasi.docx",
    name: "Ms.P.Thennarasi",
    pos: "Assistant Professor",
    image: "/media/image/Thennarasi_Photo.jpg",
    order: "7",
    email: "thennarasi.p@skct.edu.in",
  },
  {
    area: "HR and Finance",
    id: "21TMBA03",
    file: "/media/Ms.Monisha.K_-_Profile.docx",
    name: "Ms.Monisha.K",
    pos: "Assistant Professor",
    image: "/media/image/C_92_1.JPG",
    order: "8",
    email: "monisha.k@skct.edu.in",
  },
  {
    area: "Finance",
    id: "",
    file: "/media/Dr.P.Shanmugha_Priya.doc",
    name: "Dr.Shanmugha Priya P",
    pos: "Associate Professor",
    image: "/media/image/Photo.jpg",
    order: "3",
    email: "shanmughapriya.p@skct.edu.in",
  },
  {
    area: "HR & Finance",
    id: "",
    file: "/media/R.PRIYATHERSEN.doc",
    name: "Ms.Priyathersene.R",
    pos: "Assistant Professor",
    image: "/media/image/WhatsApp_Image_2021-09-03_at_1.05.41_PM.jpeg",
    order: "11",
    email: "priyathersene.r@skct.edu.in",
  },
  {
    area: "HR",
    id: "",
    file: "/media/D._Vinitha_Sree.doc",
    name: "Ms.D.Vinitha Sree",
    pos: "Assistant Professor",
    image: "/media/image/WhatsApp_Image_2021-09-07_at_2.11.01_PM.jpeg",
    order: "12",
    email: "vinithasree.d@skct.edu.in",
  },
  {
    area: "HR",
    id: "",
    file: "/media/HR_Form.doc",
    name: "Ms.Sounija",
    pos: "Assistant Professor",
    image: "/media/image/WhatsApp_Image_2021-09-09_at_3.41.01_PM_NbJ1yYq.jpeg",
    order: "14",
    email: "sounija@skct.edu.in",
  },
];

export default facultyData;
