const facultyData = [
  {
    area: "Computer Aided Design",
    id: "16TMED10",
    file: "/media/Mr.S.Ramkumar.pdf",
    name: "Mr. S. Ram Kumar",
    pos: "Assistant Professor",
    image: "/media/image/Mr.S.Ramkumar.jpg",
    order: "19",
    email: "ramkumar.s@skct.edu.in",
  },
  {
    area: "Engineering Design",
    id: "16TMED14",
    file: "/media/Mr.K.S.Raghul.pdf",
    name: "Mr. K. S. Raghul",
    pos: "Assistant Professor",
    image: "/media/image/Mr.K.S.Raghul.jpg",
    order: "20",
    email: "raghul.ks@skct.edu.in",
  },
  {
    area: "Manufacturing Engineering",
    id: "19TMED03",
    file: "/media/Dr.S.Santhosh.pdf",
    name: "Dr. S. Santhosh",
    pos: "Associate Professor",
    image: "/media/image/Dr.S.Santhosh.JPG",
    order: "8",
    email: "santhosh.s@skct.edu.in",
  },
  {
    area: "CAD/CAM",
    id: "17TMED04",
    file: "/media/Mr.M.Rajeswaran.pdf",
    name: "Mr. M. Rajeswaran",
    pos: "Assistant Professor",
    image: "/media/image/Mr.M.Rajeswaran.jpg",
    order: "21",
    email: "rajeshwaran.m@skct.edu.in",
  },
  {
    area: "Engineering Design",
    id: "19TMED04",
    file: "/media/Mr.T.Nithyanandhan.pdf",
    name: "Mr. T. Nithyanandhan",
    pos: "Assistant Professor",
    image: "/media/image/Mr.T.Nithyanandhan.JPG",
    order: "22",
    email: "nithyanandhan.t@skct.edu.in",
  },
  {
    area: "Manufacturing Engineering",
    id: "19TMED01",
    file: "/media/Mr.P.Sivaraman.pdf",
    name: "Mr. P. Sivaraman",
    pos: "Assistant Professor",
    image: "/media/image/Mr.P.Sivaraman.jpg",
    order: "23",
    email: "sivaraman.p@skct.edu.in",
  },
  {
    area: "CAD/CAM",
    id: "19TMED06",
    file: "/media/Mr.M.K.Prabhu.pdf",
    name: "Mr. M. K. Prabhu",
    pos: "Assistant Professor",
    image: "/media/image/Mr.M.K.Prabhu.jpg",
    order: "24",
    email: "prabhu.mk@skct.edu.in",
  },
  {
    area: "Thermal Engineering",
    id: "16TMED05",
    file: "/media/Mr.K.Mohan.pdf",
    name: "Mr. K. Mohan",
    pos: "Assistant Professor",
    image: "/media/image/Mr.K.Mohan.jpg",
    order: "18",
    email: "mohan.k@skct.edu.in",
  },
  {
    area: "Thermal Engineering (R&AC)",
    id: "19TMED08",
    file: "/media/Mr.K.Senthilkumar.pdf",
    name: "Mr. K. Senthil Kumar",
    pos: "Assistant Professor",
    image: "/media/image/Mr.K.Senthilkumar.JPG",
    order: "25",
    email: "senthilkumar.k@skct.edu.in",
  },
  {
    area: "Thermal Engineering",
    id: "19TMED09",
    file: "/media/Mr.A.S.Manirathnam.pdf",
    name: "Mr. A. S. Manirathnam",
    pos: "Assistant Professor",
    image: "/media/image/mani.JPG",
    order: "26",
    email: "manirathnam.as@skct.edu.in",
  },
  {
    area: "Engineering Design",
    id: "13TMED12",
    file: "/media/Dr.N.Mohanraj.pdf",
    name: "Dr. N. Mohan Raj",
    pos: "Associate Professor",
    image: "/media/image/Dr.N.Mohanraj.jpg",
    order: "7",
    email: "n.mohanraj@skct.edu.in",
  },
  {
    area: "Energy Technology",
    id: "15TMED10",
    file: "/media/Dr.S.Sundararaj.pdf",
    name: "Dr. S. Sundararaj",
    pos: "Professor",
    image: "/media/image/Dr.S.Sundararaj.jpg",
    order: "2",
    email: "s.sundararaj@skct.edu.in",
  },
  {
    area: "Casting, Welding",
    id: "06TMED02",
    file: "/media/Dr.R._Srinivasan.pdf",
    name: "Dr. R. Srinivasan",
    pos: "Professor",
    image: "/media/image/Dr.R.Srinivasan.jpg",
    order: "3",
    email: "r.srinivasan@skct.edu.in",
  },
  {
    area: "Engineering Design",
    id: "15TMED03",
    file: "/media/Mr.N.Aravindkumar.pdf",
    name: "Mr. N. Aravindkumar",
    pos: "Assistant Professor",
    image: "/media/image/Mr.N.Aravindkumar.jpg",
    order: "16",
    email: "n.aravindkumar@skct.edu.in",
  },
  {
    area: "Production Engineering",
    id: "15TMED08",
    file: "/media/Mr.Arun_Karthick.pdf",
    name: "Mr.P.Arun Karthick",
    pos: "Assistant Professor",
    image: "/media/image/Mr.P.Arunkarthick.jpg",
    order: "17",
    email: "p.arunkarthick@skct.edu.in",
  },
  {
    area: "Engineering Design",
    id: "19TMED02",
    file: "/media/Dr.P.Sakthivel.pdf",
    name: "Dr. P. Sakthivel",
    pos: "Associate Professor",
    image: "/media/image/Dr.P.Sakthivel.jpg",
    order: "4",
    email: "sakthivel.p@skct.edu.in",
  },
  {
    area: "Industrial Engineering",
    id: "18TMED03",
    file: "/media/Dr.P.Prathap.pdf",
    name: "Dr.P.Prathap",
    pos: "Professor & Head",
    image: "/media/image/hod_dUr0jaU.jpg",
    order: "1",
    email: "prathap.p@skct.edu.in",
  },
  {
    area: "Advanced Manufacturing",
    id: "20TMED02",
    file: "/media/Adharsh_j0QuA2i.pdf",
    name: "Mr. Adarsh Ajayan",
    pos: "Assistant Professor",
    image: "/media/image/DSC_82371_AeQi32t.jpg",
    order: "27",
    email: "adarshajayan@skct.edu.in",
  },
  {
    area: "Engineering Design",
    id: "22TME",
    file: "/media/Doc1_rWxhzvo.pdf",
    name: "Dr.Jeen Robert R B",
    pos: "Professor",
    image: "/media/image/profile_image_8ZjAmcN.png",
    order: "6",
    email: "jeenrobert.rb@skct.edu.in",
  },
  {
    area: "Industrial Engineering",
    id: "22TUME",
    file: "/media/images.pdf",
    name: "Dr.R.Siva kumar",
    pos: "Professor",
    image: "/media/image/images.jpg",
    order: "5",
    email: "sivakumar.r@skct.edu.in",
  },
  {
    area: "Thermal Engineering",
    id: "22TUME",
    file: "/media/white_image_pcVgW9L.pdf",
    name: "Dr.V.Karthickeyan",
    pos: "Associate Professor",
    image: "/media/image/white_image_zFRYM5I.jpg",
    order: "9",
    email: "Karthickeyan.v@skct.edu.in",
  },
  {
    area: "Engineering Design",
    id: "22TUME",
    file: "/media/white_image_2gIXDOR.pdf",
    name: "Dr.P.HariharaSakthi Sudhan",
    pos: "Associate Professor",
    image: "/media/image/white_image_iFfvzvM.jpg",
    order: "10",
    email: "HariharaSakthiSudhan.P@SKCT.EDU.IN",
  },
  {
    area: "CAD",
    id: "22TUME",
    file: "/media/white_image_F2gsWNW.pdf",
    name: "Dr.M.Varatharajulu",
    pos: "Associate Professor",
    image: "/media/image/white_image_qPhd8ZW.jpg",
    order: "11",
    email: "Varatharajulu.M@SKCT.EDU.IN",
  },
  {
    area: "Manufacturing Engineering",
    id: "22TUME",
    file: "/media/white_image_O5zV0hl.pdf",
    name: "Dr.V.S.Sreenivasan",
    pos: "Associate Professor",
    image: "/media/image/white_image_qdBiHkO.jpg",
    order: "12",
    email: "Sreenivasan.V.S@SKCT.EDU.IN",
  },
  {
    area: "CAD/CAM",
    id: "22TUME",
    file: "/media/white_image_cNXbaPS.pdf",
    name: "Dr.P.Arivalagan",
    pos: "Assistant Professor",
    image: "/media/image/white_image_ZvdnbXW.jpg",
    order: "13",
    email: "Arivalagan.p@skct.edu.in",
  },
  {
    area: "Heat Power Engineering",
    id: "22TUME",
    file: "/media/white_image_63CevXb.pdf",
    name: "Dr.S.Arivazhagan",
    pos: "Assistant Professor",
    image: "/media/image/white_image_GnoI0dy.jpg",
    order: "14",
    email: "Arivazhagan.s@skct.edu.in",
  },
  {
    area: "Energy Engineering",
    id: "22TUME",
    file: "/media/white_image_ro597gK.pdf",
    name: "Dr.F.Paul Gregory",
    pos: "Assistant Professor",
    image: "/media/image/white_image_y2mf7SD.jpg",
    order: "15",
    email: "PaulGregory.F@SKCT.EDU.IN",
  },
];

export default facultyData;
