const facultyData = [
  {
    area: "Sensors & Transducers, Measurements & Instrumentation<",
    id: "17TICE02",
    file: "/media/Website_Resume_-_ksk.pdf",
    name: "Mr.K.Saravanakumar",
    pos: "Assistant Professor",
    image: "/media/image/13.jpg",
    order: "11",
    email: "saravanakumar.k@skct.edu.in",
  },
  {
    area: "Power Systems, FACTS, Intelligent Controllers",
    id: null,
    file: "/media/Website_Resume_-_Manju.pdf",
    name: "Dr.P.Manju",
    pos: "Professor & Head",
    image: "/media/image/1_0hXZjBg.jpg",
    order: "1",
    email: "p.manju@skct.edu.in",
  },
  {
    area: "Control Systems",
    id: "19TICE01",
    file: "/media/Website_Resume_-_Ajith_xv7ZMgh.pdf",
    name: "Mr.R.Rajesh",
    pos: "Assistant Professor",
    image: "/media/image/14.jpg",
    order: "12",
    email: "rajesh.r@skct.edu.in",
  },
  {
    area: "Advanced Control Systems, PLC & DCS, Microprocessors",
    id: "11TICE01",
    file: "/media/Website_Resume_-_shanthi.pdf",
    name: "Ms.K.Shanthi",
    pos: "Assistant Professor",
    image: "/media/image/5_TSJ5Bek.jpg",
    order: "3",
    email: "k.shanthi@skct.edu.in",
  },
  {
    area: "Sensor Technology, Process Control & Automation, PLC, System Identification, Adaptive Control",
    id: "16TICE03",
    file: "/media/Website_Resume_-_Ajith.pdf",
    name: "Mr.Ajith.B.Singh",
    pos: "Assistant Professor",
    image: "/media/image/12.jpg",
    order: "10",
    email: "ajith.b.singh@skct.edu.in",
  },
  {
    area: "Renewable Energy, Soft computing, Digital systems, etc",
    id: null,
    file: "/media/Website_Resume_-_naren.pdf",
    name: "Dr.S.Narendiran",
    pos: "Associate Professor",
    image: "/media/image/4_thrnU9V.jpg",
    order: "2",
    email: "narendiran.s@skct.edu.in",
  },
  {
    area: "Renewable Energy Management & Intelligent Controllers",
    id: "16TICE02",
    file: "/media/Website_Resume_-_dhana.pdf",
    name: "Mr.J.Dhanaselvam",
    pos: "Assistant Professor",
    image: "/media/image/11.jpg",
    order: "9",
    email: "dhanaselvam.j@skct.edu.in",
  },
  {
    area: "Biosensors, Instrumentation",
    id: "13TICE01",
    file: "/media/Website_Resume_-Dilip.pdf",
    name: "Mr.S.Dilipkumar",
    pos: "Assistant Professor",
    image: "/media/image/6_nNrGFV0.jpg",
    order: "4",
    email: "s.dilipkumar@skct.edu.in",
  },
  {
    area: "Digital Control System, Biomedical Instrumentation, Embedded System",
    id: "21TICE01",
    file: "/media/Website_Resume_-_Swathi.pdf",
    name: "R.Swathi",
    pos: "Assistant Professor",
    image: "/media/image/6_nM1ixJi.png",
    order: "13.",
    email: "r.swathi@skct.edu.in",
  },
];

export default facultyData;
