const facultyData = [
  {
    area: "ENVIRONMENTAL ENGINEERING",
    id: "16tced09",
    file: "/media/1654572153_DHXDi6z.pdf",
    name: "Mr.T.P.A.ARAVIND",
    pos: "ASSISTANT PROFESSOR",
    image: "/media/image/zoho_0BXcxW3.jpg",
    order: "7",
    email: "aravind.tpa@skct.edu.in",
  },
  {
    area: "STRUCTURAL ENGINEERING",
    id: "18tced03",
    file: "/media/1654572292.pdf",
    name: "Mr.G.MANIKANDAN",
    pos: "ASSISTANT PROFESSOR",
    image: "/media/image/IMG-20220521-WA0004_ULYHuFs.jpg",
    order: "8",
    email: "manikandan.g@skct.edu.in",
  },
  {
    area: "STRUCTURAL ENGINEERING",
    id: "22TCED03",
    file: "/media/Assessment_sheet_for_record_2.pdf",
    name: "Dr.P.SUBASHREE",
    pos: "ASSOCIATE PROFESSOR",
    image: "/media/image/FACULTY.JPG",
    order: "3",
    email: "subashree.p@skct.edu.in",
  },
  {
    area: "INFRASTRUCTURE ENGINEERING",
    id: "21TCED01",
    file: "/media/schedule.pdf",
    name: "Dr.V.SATHISH KUMAR",
    pos: "ASSISTANT PROFESSOR",
    image: "/media/image/FACULTY.jpg",
    order: "4",
    email: "sathishkumar.v@skct.edu.in",
  },
  {
    area: "STRUCTURAL ENGINEERING",
    id: "",
    file: "/media/1654572153_lZL2dH4.pdf",
    name: "Dr.V.SREEVIDYA",
    pos: "PROFESSOR",
    image: "/media/image/zoho.jpg",
    order: "2",
    email: "v.sreevidya@skct.edu.in",
  },
  {
    area: "CONSTRUCTION MANAGEMENT",
    id: "15TCED003",
    file: "/media/1654572153_qVqpriU.pdf",
    name: "Dr.I.PADMANABAN",
    pos: "PROFESSOR & HEAD",
    image: "/media/image/zoho_jzljx4I.jpg",
    order: "1",
    email: "padmanaban.i@skct.edu.in",
  },
  {
    area: "STRUCTURAL AND CONSTRUCTION ENGINEERING",
    id: "19TCED03",
    file: "/media/schedule_25emAzl.pdf",
    name: "Ms.S.DHARSANA",
    pos: "ASSISTANT PROFESSOR",
    image: "/media/image/FACULTY_Gajx6vs.jpg",
    order: "9",
    email: "dharsana.s@skct.edu.in",
  },
  {
    area: "STRUCTURAL ENGINEERING",
    id: "22TCED03",
    file: "/media/Assessment_sheet_for_record_2_otzItVU.pdf",
    name: "Mr.G.JAYAKUMAR",
    pos: "ASSISTANT PROFESSOR",
    image: "/media/image/FACULTY_1g7KyQ3.JPG",
    order: "10",
    email: "jayakumar.g@skct.edu.in",
  },
  {
    area: "CONSTRUCTION MANAGEMENT",
    id: "22TCED02",
    file: "/media/Assessment_sheet_for_record_2_zOiNgCo.pdf",
    name: "Dr.N.SHANMUGANATHAN",
    pos: "ASSISTANT PROFESSOR",
    image: "/media/image/FACULTY_PpkfXm3.JPG",
    order: "5",
    email: "shanmuganathan.n@skct.edu.in",
  },
  {
    area: "STRUCTURAL ENGINEERING",
    id: "16tced03",
    file: "/media/1654572153_opqTN3O.pdf",
    name: "Mr.R.RAMESH",
    pos: "ASSISTANT PROFESSOR",
    image: "/media/image/zoho_sRuiwbf.jpg",
    order: "6",
    email: "ramesh.r@skct.edu.in",
  },
];

export default facultyData;
