const facultyData = [
  {
    area: "Network Security",
    id: "18TCSE07",
    file: "/media/kavitha_margret.pdf",
    name: "Ms.M.KAVITHA MARGRET",
    pos: "Assistant Professor",
    image: "/media/image/Kavithamargret.jpg",
    order: "11",
    email: "kavithamargret.m@skct.edu.in",
  },
  {
    area: "Internet of Things",
    id: "18TCSE12",
    file: "/media/sruthi.pdf",
    name: "Ms.M.S.SRUTHI",
    pos: "Assistant Professor",
    image: "/media/image/sruthi.jpg",
    order: "13",
    email: "sruthi.s@skct.edu.in",
  },
  {
    area: "Data Analytics",
    id: "18TCSE03",
    file: "/media/sathiyabama.pdf",
    name: "Ms.S.SATHYABAMA",
    pos: "Assistant Professor",
    image: "/media/image/sathiyabama.jpg",
    order: "8",
    email: "sathyabama.s@skct.edu.in",
  },
  {
    area: "Image Mining",
    id: "18TCSE04",
    file: "/media/sampeter.pdf",
    name: "Mr.S.SAM PETER",
    pos: "Assistant Professor",
    image: "/media/image/sampeter.jpg",
    order: "9",
    email: "sampeter.s@skct.edu.in",
  },
  {
    area: "Data mining",
    id: "17TCSE06",
    file: "/media/nive.doc",
    name: "Ms.G.NIVEDHITHA",
    pos: "Assistant Professor",
    image: "/media/image/nivedhita.jpg",
    order: "6",
    email: "nivedhitha.g@skct.edu.in",
  },
  {
    area: "Internet of Things",
    id: "17TCSE08",
    file: "/media/poorani_updated_faculty_profile_1-1.pdf",
    name: "Ms.G.POORANI",
    pos: "Assistant Professor",
    image: "/media/image/poorani_PfV8mNT.jpg",
    order: "7",
    email: "poorani.g@skct.edu.in",
  },
  {
    area: "Networks",
    id: "18TCSE08",
    file: "/media/padma_CMGNAxS.pdf",
    name: "Ms.S.PADMAVATHI",
    pos: "Assistant Professor",
    image: "/media/image/padmavathi_97npqZq.jpg",
    order: "10",
    email: "padmavathi.s@skct.edu.in",
  },
  {
    area: "Internet of Things",
    id: "08TCSE01",
    file: "/media/6.Ms.P.Anantha_Prabha_29.12020.pdf",
    name: "Ms.P.ANANTHA PRABHA",
    pos: "Associate Professor",
    image: "/media/image/anandha.gif",
    order: "4",
    email: "p.ananthaprabha@skct.edu.in",
  },
  {
    area: "Data Mining",
    id: "13TCSE07",
    file: "/media/kalpana_BjMFkK3.pdf",
    name: "Ms.P.KALPANA",
    pos: "Assistant Professor",
    image: "/media/image/kalpana.gif",
    order: "5",
    email: "p.kalpana@skct.edu.in",
  },
  {
    area: "Data Structures",
    id: "19TCSE05",
    file: "/media/sandhya.pdf",
    name: "Ms.G.SANDHYA",
    pos: "Assistant Professor",
    image: "/media/image/sandhya.jpg",
    order: "15",
    email: "sandhya.g@skct.edu.in",
  },
  {
    area: "Computer Algorithms and Computer Networks",
    id: "18TCSE01",
    file: "/media/Dr._R._KARTHIK.pdf",
    name: "Dr.R.KARTHIK",
    pos: "Associate Professor",
    image: "/media/image/Karthik_0utLiqh.jpg",
    order: "3",
    email: "karthik.r@skct.edu.in",
  },
  {
    area: "Data Mining",
    id: "19TCSE03",
    file: "/media/raghu.pdf",
    name: "Mr.T.RAGHUNATHAN",
    pos: "Assistant Professor",
    image: "/media/image/raghu.jpg",
    order: "14",
    email: "raghunathan.t@skct.edu.in",
  },
  {
    area: "Internet of Things",
    id: "18TCSE09",
    file: "/media/kiruthika_fRZUzZr.pdf",
    name: "Ms.S.KIRUTHIKA",
    pos: "Assistant Professor",
    image: "/media/image/kiruthikas_p464WRh.jpg",
    order: "12",
    email: "kiruthika.s@skct.edu.in",
  },
  {
    area: "Big Data Analytics",
    id: "21TCSE02",
    file: "/media/divya.pdf",
    name: "Ms.P.DIVYA",
    pos: "Assistant Professor",
    image: "/media/image/Divya_Photo.png",
    order: "18",
    email: "divya.p@skct.edu.in",
  },
  {
    area: "Data Analytics",
    id: "21TCSE01",
    file: "/media/ASMITHA_kp1juHA.pdf",
    name: "Ms.R.ASMITHASHREE",
    pos: "Assistant Professor",
    image: "/media/image/Capture.JPG",
    order: "17",
    email: "r.asmithashree@skct.edu.in",
  },
  {
    area: "Data Analytics, Image Processing",
    id: "20CSE",
    file: "/media/Dr_D.Jeyabharathi.pdf",
    name: "Dr.D.JEYABHARATHI",
    pos: "Assistant Professor",
    image: "/media/image/jeyabharathi.jpg",
    order: "2",
    email: "jeyabharathi.d@skct.edu.in",
  },
  {
    area: "Wireless Sensor Networks",
    id: "21CSE",
    file: "/media/Ponravikumar.pdf",
    name: "Dr.R.VIDHYA",
    pos: "Associate Professor & Head",
    image: "/media/image/IMG-20190702-WA0008.jpg",
    order: "1",
    email: "vidhya.r@skct.edu.in",
  },
  {
    area: "Web Technology",
    id: "19TCSE06",
    file: "/media/Viraja_Ravi.pdf",
    name: "Ms.VIRAJA RAVI",
    pos: "Assistant Professor",
    image: "/media/image/DSC_2530_copy.jpg",
    order: "16",
    email: "virajaravi@skct.edu.in",
  },
  {
    area: "Machine Learning, Deep Learning",
    id: "21CSE",
    file: "/media/Doc1_Xrjgp6f.pdf",
    name: "Ms.DARLING JEMIMA",
    pos: "Assistant Professor",
    image: "/media/image/profile_image_SsVkjJN.png",
    order: "20",
    email: "darlingjemima.d@skct.edu.in",
  },
  {
    area: "Image Processing, Cloud Computing",
    id: "21TCSE03",
    file: "/media/Venkatesh_Faculty_profile.pdf",
    name: "Mr. V. VENKATESH",
    pos: "Assistant Professor",
    image: "/media/image/1._Photo.jpg",
    order: "19",
    email: "venkatesh.v@skct.edu.in",
  },
  {
    area: "Data Mining",
    id: "22TCSE01",
    file: "/media/white_image_lKIEBTO.pdf",
    name: "Ms.G.SHANMUGHA PRIYA",
    pos: "Assistant Professor",
    image: "/media/image/white_image_aGuaQy1.jpg",
    order: "21",
    email: "shanmughapriya.g@skct.edu.in",
  },
  {
    area: "Data Mining",
    id: "22TCSE02",
    file: "/media/white_image_ylwHprM.pdf",
    name: "Ms.P.ILAKIYA",
    pos: "Assistant Professor",
    image: "/media/image/white_image_pDpnsgo.jpg",
    order: "22",
    email: "ilakiya.p@skct.edu.in",
  },
];

export default facultyData;
